### ISSUE TITLE
solver.cpp::find_solutions():  Test for even NCn_LS doesn't seem right

### ISSUE THREAD

**Issue by ahmogit** [mhx/gpsdo-config#1]
Re the following clause near the top of `solver.cpp::find_solutions():`
```
  if (!is_div_one_or_even(f1, lcm_freq) or !is_div_one_or_even(f2, lcm_freq))
  {
          // NCn_LS must be 1 or even
          lcm_freq *= 2;
  }
```

It seems to me that the arguments being passed to **is_div_one_or_even()** in the above clause are backwards.

Reasoning:

My interpretation of what you're trying to do there is to enforce a value of **lcm_freq** for which **NCn_LS** is either unity or an even integer. (Let's ignore the unity constraint since it doesn't apply to the CMOS part.)

So, using **f1** as an example, then it seems to me that what you want from the above clause is to conditionally scale **lcm_freq** by a factor of 2 such that

        f1 == lcm_freq / NCn_LS

for some potential even value of **NCn_LS**. This in turn requires that **lcm_freq/f1** be even.  (And similarly for **lcm_freq/f2**.)

But the second portion of the test performed by **is_div_one_or_even()** divides the first arg by the second, and then tests whether that quotient is divisible by 2. So the way that the args are currently passed in the above clause, it is the ratios **f1/lcm_freq** and **f2/lcm_freq** that are being tested for even-ness, rather that their reciprocals.

If you disagree with the above reasoning, can you please explain patiently why the test is being done the way it is?

Thank you.

**Comment by mhx** [comment]
Hi @ahmogit, thanks for your analysis!

You're absolutely correct. The arguments are indeed the wrong way around. Fortunately, the code was "self-healing" as all cases where `NCn_LS` could end up being odd were filtered out later by the `is_in_ncx_ls_range()` check.

However, if I hadn't messed up the code in the first place, that additional check wouldn't have been needed. Oh well.

I went through the whole code again while fixing the issue, adding a bit of documentation along the way so this becomes somewhat easier to read. Instead of delegating the check to a function, I've dropped the equality check (as that case isn't supported anyway) and inlined the check for odd numbers. This should have made it even easier to spot the issue. The `is_in_ncx_ls_range()` check is now only used in an assertion, as it can be expected that `NCn_LS` is now always even.

I've found yet another (also self-healing) bug: the computation of `q_max` was using `std::max(f1, f2)` where it should have been using `std::min(f1, f2)`. Also, only `q_hi` should be limited to `q_max`.

I'll push a commit with my changes.

**Comment by mhx** [comment]
I'm closing this issue as I believe it is fixed now, but please let me know if you think there are more bugs lurking in the code.

**Comment by ahmogit** [comment]
Thanks for taking care of that. 

Yes, I noticed too that that error did not actually affect the solution space, but figured might as well report it anyway, since it appeared to be JPR (as you've confirmed).

I've been playing more around with it, and have some evidence and numerous hand-worked examples showing that the **--best** option is not really finding solutions that maximize Fvco (as claimed in the writeup).  But perhaps better to report that as a separate issue, since it's unrelated to the bug reported in this thread.

Anyway, thanks for the attention to this argument-reversal issue. I'll file a new issue regarding the **--best** performance after I have some more time to play with it and characterize it better.

**Comment by mhx** [comment]
> I've been playing more around with it, and have some evidence and numerous hand-worked examples showing that the --best option is not really finding solutions that maximize Fvco (as claimed in the writeup).

I'd be really interested in those examples, they'd probably make for some good unit tests. Please definitely file a new issue for that!
