### ISSUE TITLE
Example solutions using --best which result in suboptimum f3

### ISSUE THREAD

**Issue by ahmogit** [mhx/gpsdo-config#2]
Hi Marcus,

Per your earlier request for such examples (final comment in Issue #1), please see attached writeup.

Glenn

[note.txt](https://github.com/mhx/gpsdo-config/files/10341073/note.txt)

**Comment by mhx** [comment]
Hi Glenn,

Thanks for your document!

The issue in my implementation was that it didn't actually check different values for `N31` to explore the whole reference frequency range in all cases. Essentially, `N31` was only computed once purely from the denominator of the fraction resulting from dividing the oscillator frequency be `2*N2_HS`. In quite a lot of cases, this denominator is `1`, which means `N31` is just set to `1`. As a result, the range explored for the reference frequency is limited to 2 MHz in order to not exceed the maximum spec for `f3`. Obviously, this isn't ideal, as the additional factor in `N31` allows for different factorisations when determining `N2_LS`.

I've made some changes and incorporated your test cases and the tests now pass.

I'd definitely be curious to see if your approach is more efficient in computing an optimal solution. I wouldn't be surprised if it was, as my code is really just doing a brute force scan. Especially with small output frequencies, it can get rather slow:

```
$ time ./gpsdo-config 450 675 --best 
fGPS = 1999998, N31 = 1, N1_HS = 11, NC1_LS = 989898, NC2_LS = 659932, N2_HS = 7, N2_LS = 350

real    0m1.888s
user    0m1.875s
sys     0m0.004s
```

I'll close this issue for now as I think it's fixed, but please let me know if there are cases my code isn't covering yet.

Thanks,
Marcus

**Comment by ahmogit** [comment]
Hi Marcus,

I re-cloned with your recent updates, and it does look like those particular discrepancies are indeed gone, as you indicated. I understand your explanation, makes sense.

Since I'm involved with my own implementation now though, I'm not highly motivated to do much further fiddling around with yours, but otoh, I have used yours occasionally to compare against, so if I do find any further interesting discrepancies I will certainly report them.

Re efficiency, as you had asked about: Yes, definitely there are often several orders of magnitude differences in execution time between our approaches. One particularly severe example is shown below, both run on the same (old/slow) 64b host. (I made the same mods to the output format as earlier.)

I suspect the fundamental algorithmic differences are probably even larger than those timing numbers suggest, because my implementation is currently in Octave, which, for identical numerical tasks, should generally be quite a bit slower than C + boost libs in terms of basic low-level numerical operations.

Anyway... I will let you know if any other interesting observations, questions, or discrepancies arise.

Regards,

Glenn

```


===========================================================
$ time mhx_genfp --relaxed --best 8293

  fref:   1998613
   n31:   1
    f3:   1998613.0000
 n2_hs:   11
 n2_ls:   160
  fosc:   3517558880
 n1_hs:   11
nc1_ls:   38560
nc2_ls:   38560
 fout1:   8293
 fout2:   8293

real    2m48.062s
user    2m46.707s
sys     0m0.116s


===========================================================
> runcase_optf3(8293,L)

  fref:   1998613
   n31:   1
    f3:   1998613.0000
 n2_hs:   6
 n2_ls:   292
  fosc:   3501569976
 n1_hs:   6
nc1_ls:   70372
nc2_ls:   70372
 fout1:   8293
 fout2:   8293

ET: 14.5 ms


```

**Comment by mhx** [comment]
Neat! Let me know if you publish your code! :)

**Comment by ahmogit** [comment]
I've no plans to release it under public license in the immediate future, because it has some potential commercial value vis a vis a client of mine.

Otoh, I would not object to sharing it privately with you under an NDA/acknowledgement agreement.  You could then -- if you wished -- use it to inform your code, as long as the source of any changes you made based upon it were properly acknowledged per the NDA.

Up to you, just an offer if you're interested.
